services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: false
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "127.0.0.1:5180:8080"
