// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sonrisa.Web.Data;

#nullable disable

namespace Sonrisa.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914155714_FirstRuntimeSlice")]
    partial class FirstRuntimeSlice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sonrisa.Web.Alerts.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConditionField")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition_field");

                    b.Property<string>("ConditionOperator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition_operator");

                    b.Property<double>("ConditionValue")
                        .HasColumnType("double precision")
                        .HasColumnName("condition_value");

                    b.Property<string>("ConditionValueType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition_value_type");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("enabled");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("revision");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_alerts_enabled_event_type")
                        .HasFilter("enabled = true");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_alerts_owner_id");

                    b.ToTable("alerts", "public", t =>
                        {
                            t.HasCheckConstraint("ck_alerts_codes", "event_type = 'earthquake' AND condition_field = 'magnitude' AND condition_operator = 'gte' AND condition_value_type = 'number'");

                            t.HasCheckConstraint("ck_alerts_finite_value", "condition_value > '-Infinity'::double precision AND condition_value < 'Infinity'::double precision");

                            t.HasCheckConstraint("ck_alerts_ids", "id <> '00000000-0000-0000-0000-000000000000'::uuid AND owner_id <> '00000000-0000-0000-0000-000000000000'::uuid AND revision <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_alerts_name", "name = btrim(name, U&'\\0009\\000A\\000B\\000C\\000D\\0020\\0085\\00A0\\1680\\2000\\2001\\2002\\2003\\2004\\2005\\2006\\2007\\2008\\2009\\200A\\2028\\2029\\202F\\205F\\3000') AND char_length(name) BETWEEN 1 AND 120");
                        });
                });

            modelBuilder.Entity("Sonrisa.Web.Runtime.NotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("destination");

                    b.Property<string>("LastError")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("SourceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_event_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AlertId")
                        .HasDatabaseName("ix_notification_deliveries_alert_id");

                    b.HasIndex("SourceEventId", "AlertId", "Channel")
                        .IsUnique()
                        .HasDatabaseName("ux_notification_deliveries_event_alert_channel");

                    b.ToTable("notification_deliveries", "public", t =>
                        {
                            t.HasCheckConstraint("ck_notification_deliveries_destination", "destination = btrim(destination, U&'\\0009\\000A\\000B\\000C\\000D\\0020\\0085\\00A0\\1680\\2000\\2001\\2002\\2003\\2004\\2005\\2006\\2007\\2008\\2009\\200A\\2028\\2029\\202F\\205F\\3000') AND char_length(destination) BETWEEN 2 AND 254 AND ((channel = 'slack' AND char_length(destination) <= 80 AND destination ~ '^[A-Z0-9]+$') OR (channel = 'email' AND destination ~ '^[^[:space:][:cntrl:]@]+@[^[:space:][:cntrl:]@]+$'))");

                            t.HasCheckConstraint("ck_notification_deliveries_identity", "id <> '00000000-0000-0000-0000-000000000000'::uuid AND source_event_id <> '00000000-0000-0000-0000-000000000000'::uuid AND alert_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_notification_deliveries_status", "channel IN ('slack', 'email')\nAND status IN ('pending', 'processing', 'sent', 'failed', 'unsupported')\nAND (last_error IS NULL OR last_error ~ '^[a-z][a-z0-9_]*$')\nAND ((channel = 'email' AND status = 'unsupported' AND sent_at IS NULL\n    AND last_error = 'transport_not_implemented')\n  OR (channel = 'slack' AND (\n    (status = 'pending' AND sent_at IS NULL AND last_error IS NULL)\n    OR (status = 'processing' AND sent_at IS NULL\n        AND (last_error IS NULL OR last_error = 'delivery_outcome_unknown'))\n    OR (status = 'sent' AND sent_at IS NOT NULL AND last_error IS NULL)\n    OR (status = 'failed' AND sent_at IS NULL AND last_error IS NOT NULL)))) IS TRUE");
                        });
                });

            modelBuilder.Entity("Sonrisa.Web.Runtime.SourceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer")
                        .HasColumnName("contract_version");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("processing_status");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt", "Id")
                        .HasDatabaseName("ix_source_events_pending")
                        .HasFilter("processing_status = 'pending'");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_source_events_source_external_id");

                    b.ToTable("source_events", "public", t =>
                        {
                            t.HasCheckConstraint("ck_source_events_data", "CASE WHEN jsonb_typeof(data) = 'object'\n    AND jsonb_typeof(data->'magnitude') = 'number'\n    AND data = jsonb_build_object('magnitude', data->'magnitude')\nTHEN ((data->>'magnitude')::double precision > '-Infinity'::double precision\n    AND (data->>'magnitude')::double precision < 'Infinity'::double precision) IS TRUE\nELSE false END");

                            t.HasCheckConstraint("ck_source_events_identity", "id <> '00000000-0000-0000-0000-000000000000'::uuid AND contract_version = 1 AND source IN ('usgs', 'demo.usgs') AND external_id ~ '^[!-~]+$' AND event_type = 'earthquake' AND title = btrim(title, U&'\\0009\\000A\\000B\\000C\\000D\\0020\\0085\\00A0\\1680\\2000\\2001\\2002\\2003\\2004\\2005\\2006\\2007\\2008\\2009\\200A\\2028\\2029\\202F\\205F\\3000') AND char_length(title) BETWEEN 1 AND 300 AND title !~ '[[:cntrl:]]' AND (source_url IS NULL OR (source_url = btrim(source_url, U&'\\0009\\000A\\000B\\000C\\000D\\0020\\0085\\00A0\\1680\\2000\\2001\\2002\\2003\\2004\\2005\\2006\\2007\\2008\\2009\\200A\\2028\\2029\\202F\\205F\\3000') AND source_url ~ '^https?://[^[:space:][:cntrl:]]+$'))");

                            t.HasCheckConstraint("ck_source_events_status", "processing_status IN ('pending', 'evaluated')");
                        });
                });

            modelBuilder.Entity("Sonrisa.Web.Users.UserNotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EmailDestination")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email_destination");

                    b.Property<Guid>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("revision");

                    b.Property<string>("SlackDestination")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slack_destination");

                    b.HasKey("Id");

                    b.ToTable("users", "public", t =>
                        {
                            t.HasCheckConstraint("ck_users_destinations", "(email_destination IS NOT NULL OR slack_destination IS NOT NULL) AND (email_destination IS NULL OR (email_destination = btrim(email_destination, U&'\\0009\\000A\\000B\\000C\\000D\\0020\\0085\\00A0\\1680\\2000\\2001\\2002\\2003\\2004\\2005\\2006\\2007\\2008\\2009\\200A\\2028\\2029\\202F\\205F\\3000') AND char_length(email_destination) BETWEEN 1 AND 254)) AND (slack_destination IS NULL OR (slack_destination = btrim(slack_destination, U&'\\0009\\000A\\000B\\000C\\000D\\0020\\0085\\00A0\\1680\\2000\\2001\\2002\\2003\\2004\\2005\\2006\\2007\\2008\\2009\\200A\\2028\\2029\\202F\\205F\\3000') AND char_length(slack_destination) BETWEEN 2 AND 80 AND slack_destination ~ '^[A-Z0-9]+$'))");

                            t.HasCheckConstraint("ck_users_ids", "id <> '00000000-0000-0000-0000-000000000000'::uuid AND revision <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("Sonrisa.Web.Alerts.Alert", b =>
                {
                    b.HasOne("Sonrisa.Web.Users.UserNotificationSettings", "Owner")
                        .WithMany("Alerts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Sonrisa.Web.Runtime.NotificationDelivery", b =>
                {
                    b.HasOne("Sonrisa.Web.Alerts.Alert", null)
                        .WithMany()
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sonrisa.Web.Runtime.SourceEvent", null)
                        .WithMany()
                        .HasForeignKey("SourceEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonrisa.Web.Users.UserNotificationSettings", b =>
                {
                    b.Navigation("Alerts");
                });
#pragma warning restore 612, 618
        }
    }
}
