// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sonrisa.Web.Data;

#nullable disable

namespace Sonrisa.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914184146_RemoveObsoleteRuntimeState")]
    partial class RemoveObsoleteRuntimeState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sonrisa.Web.Alerts.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConditionField")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition_field");

                    b.Property<string>("ConditionOperator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition_operator");

                    b.Property<double>("ConditionValue")
                        .HasColumnType("double precision")
                        .HasColumnName("condition_value");

                    b.Property<string>("ConditionValueType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition_value_type");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("enabled");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("revision");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_alerts_enabled_event_type")
                        .HasFilter("enabled = true");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_alerts_owner_id");

                    b.ToTable("alerts", "public", t =>
                        {
                            t.HasCheckConstraint("ck_alerts_codes", "event_type = 'earthquake' AND condition_field = 'magnitude' AND condition_operator = 'gte' AND condition_value_type = 'number'");

                            t.HasCheckConstraint("ck_alerts_finite_value", "condition_value > '-Infinity'::double precision AND condition_value < 'Infinity'::double precision");

                            t.HasCheckConstraint("ck_alerts_ids", "id <> '00000000-0000-0000-0000-000000000000'::uuid AND owner_id <> '00000000-0000-0000-0000-000000000000'::uuid AND revision <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_alerts_name", "name = btrim(name, U&'\\0009\\000A\\000B\\000C\\000D\\0020\\0085\\00A0\\1680\\2000\\2001\\2002\\2003\\2004\\2005\\2006\\2007\\2008\\2009\\200A\\2028\\2029\\202F\\205F\\3000') AND char_length(name) BETWEEN 1 AND 120");
                        });
                });

            modelBuilder.Entity("Sonrisa.Web.Users.UserNotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EmailDestination")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email_destination");

                    b.Property<Guid>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("revision");

                    b.Property<string>("SlackDestination")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slack_destination");

                    b.HasKey("Id");

                    b.ToTable("users", "public", t =>
                        {
                            t.HasCheckConstraint("ck_users_destinations", "(email_destination IS NOT NULL OR slack_destination IS NOT NULL) AND (email_destination IS NULL OR (email_destination = btrim(email_destination, U&'\\0009\\000A\\000B\\000C\\000D\\0020\\0085\\00A0\\1680\\2000\\2001\\2002\\2003\\2004\\2005\\2006\\2007\\2008\\2009\\200A\\2028\\2029\\202F\\205F\\3000') AND char_length(email_destination) BETWEEN 1 AND 254)) AND (slack_destination IS NULL OR (slack_destination = btrim(slack_destination, U&'\\0009\\000A\\000B\\000C\\000D\\0020\\0085\\00A0\\1680\\2000\\2001\\2002\\2003\\2004\\2005\\2006\\2007\\2008\\2009\\200A\\2028\\2029\\202F\\205F\\3000') AND char_length(slack_destination) BETWEEN 2 AND 80 AND slack_destination ~ '^[A-Z0-9]+$'))");

                            t.HasCheckConstraint("ck_users_ids", "id <> '00000000-0000-0000-0000-000000000000'::uuid AND revision <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("Sonrisa.Web.Alerts.Alert", b =>
                {
                    b.HasOne("Sonrisa.Web.Users.UserNotificationSettings", "Owner")
                        .WithMany("Alerts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Sonrisa.Web.Users.UserNotificationSettings", b =>
                {
                    b.Navigation("Alerts");
                });
#pragma warning restore 612, 618
        }
    }
}
