// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sonrisa.Web.Data;

#nullable disable

namespace Sonrisa.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914125733_InitialAlertConfiguration")]
    partial class InitialAlertConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sonrisa.Web.Alerts.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConditionField")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition_field");

                    b.Property<string>("ConditionOperator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition_operator");

                    b.Property<double>("ConditionValue")
                        .HasColumnType("double precision")
                        .HasColumnName("condition_value");

                    b.Property<string>("ConditionValueType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition_value_type");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("enabled");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("revision");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_alerts_enabled_event_type")
                        .HasFilter("enabled = true");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_alerts_owner_id");

                    b.ToTable("alerts", "public", t =>
                        {
                            t.HasCheckConstraint("ck_alerts_codes", "event_type = 'earthquake' AND condition_field = 'magnitude' AND condition_operator = 'gte' AND condition_value_type = 'number'");

                            t.HasCheckConstraint("ck_alerts_finite_value", "condition_value > '-Infinity'::double precision AND condition_value < 'Infinity'::double precision");

                            t.HasCheckConstraint("ck_alerts_ids", "id <> '00000000-0000-0000-0000-000000000000'::uuid AND owner_id <> '00000000-0000-0000-0000-000000000000'::uuid AND revision <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_alerts_name", "name = btrim(name) AND char_length(name) BETWEEN 1 AND 120");
                        });
                });

            modelBuilder.Entity("Sonrisa.Web.Alerts.AlertChannel", b =>
                {
                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<string>("ChannelType")
                        .HasColumnType("text")
                        .HasColumnName("channel_type");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("destination");

                    b.HasKey("AlertId", "ChannelType");

                    b.ToTable("alert_channels", "public", t =>
                        {
                            t.HasCheckConstraint("ck_alert_channels_destination", "destination = btrim(destination) AND char_length(destination) BETWEEN 1 AND 254");

                            t.HasCheckConstraint("ck_alert_channels_type", "channel_type IN ('email', 'slack')");
                        });
                });

            modelBuilder.Entity("Sonrisa.Web.Alerts.AlertChannel", b =>
                {
                    b.HasOne("Sonrisa.Web.Alerts.Alert", "Alert")
                        .WithMany("Channels")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("Sonrisa.Web.Alerts.Alert", b =>
                {
                    b.Navigation("Channels");
                });
#pragma warning restore 612, 618
        }
    }
}
